Repository wanted-pre-onboarding-09/wanted-codestates-project-9-8, pull requests merged in 2022-03, with the labels that each got.

#33 feature/31_home_css
  src/App.js
  src/components/common/Header.js
  src/components/common/Pagination.js
  src/components/home/FormList.js
  src/components/home/Search.js
  src/index.css
Labels: Fix

#36 Feature/28 add toast modal
  src/components/common/Toast.js
  src/components/home/FormList.js
  src/components/list/List.js
  src/components/modal/Modal.js
  src/components/modal/ModalButton.js
Labels: enhancement

#42 Fix/38 toast
  src/components/common/Toast.js
  src/components/home/FormList.js
  src/components/list/List.js
  src/components/modal/Modal.js
Labels: enhancement, Fix

#45 Feature/44 resize textarea
  src/components/modal/Modal.js
Labels: enhancement

#51 Feature/50 modal redux
  src/components/home/FormList.js
  src/components/list/List.js
  src/components/modal/Modal.js
  src/store/index.js
  src/store/reducers/modalSlice.js
  src/store/reducers/toastSlice.js
Labels: enhancement
